# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        GOOS: ["linux", "windows"]
        GOARCH: ["amd64", "386"]
        include:
          - GOOS: windows
            EXT: .exe

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        mkdir -p output
        go build -v ./... -o ./output/go-passgen-$GOOS-$GOARCH$EXT
      env:
        GOOS: ${{ matrix.GOOS }}
        GOARCH: ${{ matrix.GOARCH }}
        EXT: ${{ matrix.EXT }}
      shell: bash

    - name: Test
      run: go test -v ./...
    
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: output
        path: output/*
